### ISSUE TITLE
Apparently LibSodium is missing

### ISSUE THREAD

**Issue by Naruk-TUBK** [ihrigb/node-red-contrib-doorbird-ultimate#16]
When an UDP Packets arrives i get the following nodered log entry and nodered crashes:

11 Apr 00:07:50 - [error] TypeError: sodium.crypto_pwhash is not a function
    at DoorbirdUdpSocket.<anonymous> (/data/node_modules/doorbird/dist/index.js:121:55)
    at step (/data/node_modules/doorbird/dist/index.js:56:23)
    at Object.next (/data/node_modules/doorbird/dist/index.js:37:53)
    at fulfilled (/data/node_modules/doorbird/dist/index.js:28:58)

How can i get it running?

**Comment by ihrigb** [comment]
@Naruk-TUBK can you provide more information on the runtime of Node Red (e.g. where do you run it or how do you run it)?

**Comment by ihrigb** [comment]
This issue may also be related to an issue in the underlying library: https://github.com/ihrigb/node-doorbird/issues/74

This is fixed and the node red plugin is updated: https://github.com/ihrigb/node-red-contrib-doorbird-ultimate/releases/tag/v1.2.3

Feel free to test it and let me know, if there are further issues.
